export const ELEMENTS = {

    site: 'https://www.enjoei.com.br/',
    fecharpop01: '[data-test=button-fechar-modal] > .o-icon',
    pesquisarProd: '[data-test=input-filtro-pesquisa]',
    selecionarProd: ':nth-child(3) > .c-product-card > .c-product-card__img-wrapper > a > [data-test=image-prod]',
    addSacolinha: '[data-test=button-adicionar-sacolinha]',
    emailLogin: '[data-test=input-email]',
    senhaLogin: '[data-test=input-password]',
    botãoEntrar: '[data-test=button-login-entrar]',
    finalizarCompra: '.c-seller-bar__actions-submit',
    cep: '#zipcode',
    rua: '#street',
    bairro: '#neighborhood',
    númeroEnd: '#number',
    complemento: '#complement',
    aceiteNovoEnd: ':nth-child(8) > .o-form__field > .o-checkbox > .o-checkbox__blank',
    botãoContinuar: ':nth-child(9) > .o-button',
    continuarEndereço:':nth-child(1) > .-xs-primary',
    nTelefone: '#phone',
    nCPF: '#taxpayer_registry',
    dataNascimento: '#birth-date',
    garantirCPF: ':nth-child(4) > .o-form__field > .o-checkbox > .o-checkbox__blank',
    botãoContinuarpósCPF: ':nth-child(5) > .o-button',
    pagarBoleto: '[data-method="bank_slip"]',
    aceitoTermos: '[data-panels-name="payment-bank-slip"] > .l-checkout-payment-option > .Form__wrapper > .Checkbox > .Checkbox__label',
    botãoComprar: '[data-panels-name="payment-bank-slip"] > .l-checkout-payment-option > .Form__wrapper > .-xs-medium',
}