export const ELEMENTS = {

    url: 'https://www.enjoei.com.br/',
    popup: '[data-test=button-fechar-modal] > .o-icon > use',
    search: '[data-test=input-filtro-pesquisa]',
    filtro_etc_tal: '[data-test=button-etctal]',
    filtro_categoria:'[data-test=dropdown-marca]',
    filtro_outros: '.is-open > .-xs-gutter-medium > :nth-child(1) > .o-checkbox > .o-checkbox__blank',
    filtro_preco: '[data-test=dropdown-preco]',
    preco1: '[data-test=input-preco-de]',
    preco2: '[data-test=input-preco-ate]',
    aplicar_filtro_preco: '[data-test=button-preco-aplicar]',
    filtro_novidades:'[data-test=dropdown-novid]',
    ultimas24h:'.c-product-feed-filters__content-body > .is-open > div > :nth-child(1)',
    tenis: ':nth-child(4) > .c-product-card',
    yeyezar: '[data-test=button-yeye]',
    login_email: '[data-test=button-entrar-email]',
    email: '[data-test=input-email]',
    senha: '[data-test=input-password]',
    botao_login: '[data-test=button-yeye] > .o-icon',
    avatar: '[data-test=button-bar-avatar] > .o-avatar',
    yeyezados: '[data-test=button-menu-yeyezados]',
    validar_yeyezados: '.c-toggle__area',
    }